### ISSUE TITLE
Professors with similar names

### ISSUE THREAD

**Issue by msimmon6** [tybug/testudoplus#1]
I like what you've done! I also made a few modifications of my own. There's a small issue currently with Jose Calderon and Jose Naharro-Calderon, for example - Jose Calderon's RMP score actually pulls Naharro-Calderon's. If the instructorInfo array in the getRecordId function has multiple values after the filter, you should filter even more to fix this.

**Comment by Liam-DeVoe** [comment]
should be closed by https://github.com/tybug/testudoplus/commit/0872d5a691bc33d64b46b8980a5b07dcb63ffb8d (https://github.com/tybug/testudoplus/commit/0872d5a691bc33d64b46b8980a5b07dcb63ffb8d#diff-d33e069e7bc162ec0fbb20b88eb8c25e8067567a114a38d0566e55d474895e8eR100-R109 in particular)
