### ISSUE TITLE
PlanetTerp GPAs and professor ratings not showing

### ISSUE THREAD

**Issue by leannebrady** [tybug/testudoplus#6]

**Comment by Liam-DeVoe** [comment]
works fine here. Can you provide a url which isn't working for you? Have you made sure that you've accepted requests from tampermonkey to make outbound http requests?

**Comment by leannebrady** [comment]
https://app.testudo.umd.edu/soc/202208/CMSC

It's not any particular URL, its just not working in general. This is what it displays:

<img width="1122" alt="Screen Shot 2022-09-08 at 6 51 44 PM" src="https://user-images.githubusercontent.com/109229029/189239626-f55f00d3-5f4a-4745-86a0-03ba04a7a02a.png">

I'm not sure how to accept requests from tampermonkey, as I don't seem to have any. It's worked fine in the past it only recently stopped working.

**Comment by Liam-DeVoe** [comment]
Hmm. If it's worked in the past on your computer, that probably isn't the issue.

I'm concerned why we have different ratemyprofessor ratings for ashok agrawala - here's what I see:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/31628143/189240272-3ca9d4bc-2b73-442b-b359-c2697e8cdc99.png">


Can you open the developer console (f12 on chrome) on that page and copy+paste the full contents of the console here? (here's what mine looks like, for reference) 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/31628143/189240457-a08f6d49-9730-40ea-b708-20170e175cdb.png">

**Comment by leannebrady** [comment]
Seems like the PlanetTerp info works now (I deleted and reinstalled the plugin which I should've tried before)

<img width="1139" alt="Screen Shot 2022-09-08 at 7 05 04 PM" src="https://user-images.githubusercontent.com/109229029/189241261-85a0638f-d9c2-4606-8ae9-28bce0d9b982.png">

As for ratemyprofessor, it looks accurate on my end to what I found when I google searched their rating. 
This is what showed on my developer console:

<img width="1400" alt="Screen Shot 2022-09-08 at 7 15 48 PM" src="https://user-images.githubusercontent.com/109229029/189241943-f0b00b2d-be98-4321-9612-a6ae2031ad4e.png">

DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

Looks different on MacOS so I don't know if that was what you were looking for.

**Comment by Liam-DeVoe** [comment]
Weird, my ratemyprofessor rating must be wrong for some reason then. Will have to look into that.

That console was indeed was I was looking for, but it seems totally normal. No idea why the script was broken for you. I'm glad reinstalling fixed it though.
